#### Preamble ####
# Purpose: Figure 1 replication
# Author: Yunzhao Li, Yang Cheng, Wentao Sun
# Date: 14 February 2024
# Contact: yunzhao.li@mail.utoronto.ca
# License: MIT
# Pre-requisites: download_data.R, data_cleaning.R

## Data Sources:
# Data about frequencies and percentages generated by the descriptives and 
# propTest2 functions in data_cleaning.R



#### Workspace setup ####
# Load libraries
library(ggplot2)
library(scales)
library(knitr)
library(MBESS)
library(psych)
library(dplyr) 
library(Hmisc)
library(effsize)
library(jmv)
library(Rcpp)
library(reshape2)
library(readr)
library(janitor)
library(tidyverse)
library(kableExtra)


# Ensure that the percentages are divided by 100 to be in the correct format
data2 <- data.frame(
  Category = c('Regret', 'Social norms (injunctive)', 'Social norms (descriptive)', 'Negative affect'),
  Smith = c(7.9 / 100, 4.7 / 100, 90.6 / 100, 7.3 / 100), # Convert to proportions
  Jones = c(92.1 / 100, 95.3 / 100, 9.4 / 100, 92.7 / 100) # Convert to proportions
)

# Melt the data for use with ggplot2
data_melted <- melt(data2, id.vars='Category')

# Create the bar plot with specified colors and corrected percentage values
ggplot(data_melted, aes(x = Category, y = value, fill = variable)) +
  geom_bar(stat = 'identity', position = position_dodge(width = 0.9)) +
  scale_fill_manual(values = c('Smith' = '#1f77b4', 'Jones' = '#d62728')) +
  theme_minimal() +
  labs(x = '', y = 'Percentage (%)', fill = '') +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = 'bottom',
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    plot.title = element_text(hjust = 0.5)
  ) +
  scale_y_continuous(labels = percent_format()) + # This will ensure y-axis is formatted as percentage
  ggtitle('Proportions for regret, social norms, and negative affect')